node_limit.node_limit.*:
  type: config_entity
  label: 'NodeLimit config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
